Fix for JERSEY-2488 : Declaring a dependency on jersey-client causes NoClassDefFoundError - fixed user guide
Change-Id: Ifeda05277baa07f0a39388d48f183c66d766eb86
Signed-off-by: Jakub Podlesak <jakub.podlesak@oracle.com>